spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springsecuritydb
    username: root
    password: Test1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false

#https://auth0.com/docs/tokens/json-web-tokens/json-web-token-claims
#https://www.javainuse.com/spring/boot-jwt
#https://medium.com/omarelgabrys-blog/microservices-with-spring-boot-authentication-with-jwt-part-3-fafc9d7187e8
#https://github.com/OmarElGabry/microservices-spring-boot
#https://www.marcobehler.com/guides/spring-security